const express = require('express');
const Expense = require('../models/Expense');
const authMiddleware = require('../middleware/auth');
const router = express.Router();

router.use(authMiddleware);

// Get all expenses for logged-in user with pagination
router.get('/', async (req, res) => {
  try {
    const { page = 1, limit = 50, type, startDate, endDate } = req.query;
    
    console.log('=== Fetching Expenses ===');
    console.log('User ID:', req.userId);
    
    // Build query with filters
    const query = { userId: req.userId };
    if (type) query.type = type;
    if (startDate || endDate) {
      query.date = {};
      if (startDate) query.date.$gte = new Date(startDate);
      if (endDate) query.date.$lte = new Date(endDate);
    }
    
    // Use lean() for faster queries (returns plain JS objects instead of Mongoose documents)
    const expenses = await Expense.find(query)
      .sort({ date: -1 })
      .limit(limit * 1)
      .skip((page - 1) * limit)
      .select('-__v') // Exclude version key
      .lean() // Faster queries
      .exec();
    
    // Get total count for pagination
    const count = await Expense.countDocuments(query);
    
    console.log(`Found ${expenses.length} expenses (${count} total)`);
    
    // Format response
    const formattedExpenses = expenses.map(expense => ({
      id: expense._id,
      userId: expense.userId,
      amount: expense.amount,
      type: expense.type || 'debit',
      category: expense.category,
      description: expense.description,
      date: expense.date,
      isAutoGenerated: expense.isAutoGenerated || false,
      createdAt: expense.createdAt
    }));
    
    res.json({
      expenses: formattedExpenses,
      totalPages: Math.ceil(count / limit),
      currentPage: page,
      totalExpenses: count
    });
  } catch (error) {
    console.error('Error fetching expenses:', error);
    res.status(500).json({ message: 'Error fetching expenses', error: error.message });
  }
});

// Create new expense
router.post('/', async (req, res) => {
  try {
    const { amount, type, category, description, date, isAutoGenerated } = req.body;
    
    console.log('=== Creating Expense ===');
    console.log('User ID:', req.userId);
    console.log('Request Body:', req.body);
    
    const expense = new Expense({
      userId: req.userId,
      amount: parseFloat(amount),
      type: type || 'debit',
      category,
      description,
      date: date || new Date(),
      isAutoGenerated: isAutoGenerated || false
    });
    
    console.log('Expense object before save:', expense);
    
    const savedExpense = await expense.save();
    console.log('✓ Expense saved successfully to MongoDB!');
    console.log('Saved Expense ID:', savedExpense._id);
    console.log('Saved Expense Data:', savedExpense);
    
    // Format response to match frontend expectations
    const formattedExpense = {
      id: savedExpense._id,
      userId: savedExpense.userId,
      amount: savedExpense.amount,
      type: savedExpense.type,
      category: savedExpense.category,
      description: savedExpense.description,
      date: savedExpense.date,
      isAutoGenerated: savedExpense.isAutoGenerated,
      createdAt: savedExpense.createdAt
    };
    
    res.status(201).json(formattedExpense);
  } catch (error) {
    console.error('✗ Error creating expense:', error);
    console.error('Error details:', error.message);
    if (error.errors) {
      console.error('Validation errors:', error.errors);
    }
    res.status(500).json({ message: 'Error creating expense', error: error.message });
  }
});

// Update expense
router.put('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const { amount, type, category, description, date } = req.body;
    
    const expense = await Expense.findOne({ _id: id, userId: req.userId });
    
    if (!expense) {
      return res.status(404).json({ message: 'Expense not found' });
    }

    // Prevent editing auto-generated expenses
    if (expense.isAutoGenerated) {
      return res.status(403).json({ message: 'Cannot edit auto-generated transactions' });
    }
    
    expense.amount = parseFloat(amount);
    expense.type = type || expense.type;
    expense.category = category;
    expense.description = description;
    expense.date = date;
    
    await expense.save();
    console.log('Expense updated:', expense._id);
    
    // Format response to match frontend expectations
    const formattedExpense = {
      id: expense._id,
      userId: expense.userId,
      amount: expense.amount,
      type: expense.type,
      category: expense.category,
      description: expense.description,
      date: expense.date,
      isAutoGenerated: expense.isAutoGenerated,
      createdAt: expense.createdAt
    };
    
    res.json(formattedExpense);
  } catch (error) {
    console.error('Error updating expense:', error);
    res.status(500).json({ message: 'Error updating expense', error: error.message });
  }
});

// Delete expense
router.delete('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    
    const expense = await Expense.findOne({ _id: id, userId: req.userId });
    
    if (!expense) {
      return res.status(404).json({ message: 'Expense not found' });
    }

    // Prevent deleting auto-generated expenses
    if (expense.isAutoGenerated) {
      return res.status(403).json({ message: 'Cannot delete auto-generated transactions' });
    }
    
    await Expense.findOneAndDelete({ _id: id, userId: req.userId });
    
    console.log('Expense deleted:', id);
    res.json({ message: 'Expense deleted' });
  } catch (error) {
    console.error('Error deleting expense:', error);
    res.status(500).json({ message: 'Error deleting expense', error: error.message });
  }
});

// Get expense analysis with date range
router.get('/analysis', async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    
    let query = { userId: req.userId };
    
    if (startDate && endDate) {
      const end = new Date(endDate);
      end.setHours(23, 59, 59, 999); // include the full end day
      query.date = {
        $gte: new Date(startDate),
        $lte: end
      };
    }
    
    const expenses = await Expense.find(query);
    
    const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
    const categoryBreakdown = expenses.reduce((acc, e) => {
      acc[e.category] = (acc[e.category] || 0) + e.amount;
      return acc;
    }, {});

    // Daily spending trend
    const dailySpending = expenses.reduce((acc, e) => {
      const day = new Date(e.date).toISOString().split('T')[0];
      acc[day] = (acc[day] || 0) + e.amount;
      return acc;
    }, {});
    const dailyTrend = Object.entries(dailySpending)
      .sort(([a], [b]) => new Date(a) - new Date(b))
      .map(([date, amount]) => ({ date, amount: parseFloat(amount.toFixed(2)) }));

    const daysDiff = startDate && endDate 
      ? Math.max(1, Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24)))
      : 1;
    const avgPerDay = expenses.length > 0 ? totalSpent / daysDiff : 0;
    const highestCategory = Object.entries(categoryBreakdown).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';
    
    // Format expenses to match frontend expectations
    const formattedExpenses = expenses.map(expense => ({
      id: expense._id,
      userId: expense.userId,
      amount: expense.amount,
      category: expense.category,
      description: expense.description,
      date: expense.date,
      createdAt: expense.createdAt
    }));
    
    console.log(`Analysis: ${expenses.length} expenses, total: $${totalSpent.toFixed(2)}`);
    
    res.json({
      totalSpent,
      categoryBreakdown,
      expenseCount: expenses.length,
      avgPerDay,
      highestCategory,
      dailyTrend,
      expenses: formattedExpenses
    });
  } catch (error) {
    console.error('Error fetching analysis:', error);
    res.status(500).json({ message: 'Error fetching analysis', error: error.message });
  }
});

module.exports = router;
