const cron = require('node-cron');
const User = require('../models/User');
const Expense = require('../models/Expense');

// Run daily at midnight to check for salary credits
const startSalaryCron = () => {
  // Run every day at 00:01 AM
  cron.schedule('1 0 * * *', async () => {
    try {
      console.log('=== Running Salary Auto-Credit Check ===');
      const today = new Date().getDate();
      
      // Find all salaried users whose salary date matches today
      const users = await User.find({ 
        isSalaried: true, 
        salaryDate: today,
        monthlySalary: { $gt: 0 }
      });
      
      console.log(`Found ${users.length} users with salary date on ${today}`);
      
      for (const user of users) {
        // Check if salary was already credited this month
        const startOfMonth = new Date();
        startOfMonth.setDate(1);
        startOfMonth.setHours(0, 0, 0, 0);
        
        const existingSalary = await Expense.findOne({
          userId: user._id,
          type: 'credit',
          category: 'Salary',
          isAutoGenerated: true,
          date: { $gte: startOfMonth }
        });
        
        if (existingSalary) {
          console.log(`Salary already credited for user ${user.name} this month`);
          continue;
        }
        
        // Create auto salary credit
        const salaryCredit = new Expense({
          userId: user._id,
          amount: user.monthlySalary,
          type: 'credit',
          category: 'Salary',
          description: `Monthly Salary - Auto Credit`,
          date: new Date(),
          isAutoGenerated: true
        });
        
        await salaryCredit.save();
        console.log(`✓ Auto-credited salary ₹${user.monthlySalary} for user ${user.name}`);
      }
      
      console.log('=== Salary Auto-Credit Check Completed ===');
    } catch (error) {
      console.error('Error in salary cron job:', error);
    }
  });
  
  console.log('✓ Salary auto-credit cron job started');
};

module.exports = { startSalaryCron };
