const mongoose = require('mongoose');

const expenseSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true // Index for faster queries
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: 0
  },
  type: {
    type: String,
    required: true,
    enum: ['debit', 'credit'],
    default: 'debit',
    index: true // Index for filtering by type
  },
  category: {
    type: String,
    required: [true, 'Category is required'],
    enum: ['Food', 'Transport', 'Entertainment', 'Shopping', 'Bills', 'Healthcare', 'Salary', 'Income', 'Other'],
    index: true // Index for category filtering
  },
  description: {
    type: String,
    required: [true, 'Description is required'],
    trim: true
  },
  date: {
    type: Date,
    required: true,
    default: Date.now,
    index: true // Index for date sorting/filtering
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

// Compound index for common query patterns
expenseSchema.index({ userId: 1, date: -1 }); // Most common: get user's expenses sorted by date
expenseSchema.index({ userId: 1, type: 1, date: -1 }); // Filter by type and sort

module.exports = mongoose.model('Expense', expenseSchema);
